### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by uhhams** [PrincessCyanMarine/Simple-Veinminer#2]
how do I format the whitelist/blacklist so that it only allows logs and ores to be mined?

**Comment by uhhams** [comment]
<img width="681" alt="Screen Shot 2022-03-29 at 7 02 22 PM" src="https://user-images.githubusercontent.com/96365922/160735873-e240354a-6534-46d0-9715-6ebe079bff1b.png">
this is what I did ^^^

**Comment by PrincessCyanMarine** [comment]
The list should be composed of identifiers or tags between quotes, separated by commas

So if, for example, you want to filter dirt and stone you would use

```
list=[
    "minecraft:dirt",
    "minecraft:stone"
]
```


By default, the mod adds all vanilla ores (including deepslate variants) to the *#c:ores* tag
So to filter only ores and logs,

```
list=[
    "#c:ores",
    "#minecraft:logs"
]
```

can be used


When it comes to modded ores, you'll most likely need to filter each one individually like "mod1:silver_ore", "mod2:uranium", etc.


Hope this helps
If there's anything you don't understand, feel free to ask!

**Comment by uhhams** [comment]
I did the indiviual modding for the Mythic Metals mod but it doesnt seem to work in-game. do I have to specify some things In the confic to make it recognise it? <img width="676" alt="Screen Shot 2022-04-16 at 1 44 31 PM" src="https://user-images.githubusercontent.com/96365922/163690837-99ab345b-abe1-44d9-bd5d-a590a4bc6b95.png">

**Comment by PrincessCyanMarine** [comment]
"#" should only be used for tags

On your config, remove it for every block except for "#c:ores" and "#c:logs"

**Comment by uhhams** [comment]
thanks that worked ! :)
